version: "3"
dir: ../
# -----------------------------------------------------------------------------
# -- Project Config ------------------------------------------------------------
# -----------------------------------------------------------------------------
vars:
  VERSION:
    sh: echo $(git describe --tags --abbrev=0)
    default: "v0.0.0"
  COMMIT:
    sh: git log -n 1 --format=%h
    default: "0000000"
  DATE:
    sh: date -u '+%m/%d/%y %I:%M:%S%p'
    default: "1970-01-01_00:00:00AM"

# ----------------------------------------------------------------------------
# -- Public Tasks ------------------------------------------------------------
# ----------------------------------------------------------------------------
tasks:
  default:
    desc: Build the binary for mac, linux
    cmds:
      - task: go-build
        vars:
          OS: linux
          ARCH: amd64
      - task: go-build
        vars:
          OS: linux
          ARCH: arm64
      - task: go-build
        vars:
          OS: darwin
          ARCH: amd64

  release:
    desc: Build the binary for docker
    depends: [build]
    cmds:
      - task: docker-tag-push
        vars:
          IMAGE: sonr-faucet
          REGISTRY: ghcr.io/sonrhq
      - task: docker-tag-push
        vars:
          IMAGE: sonr-base
          REGISTRY: ghcr.io/sonrhq
      - task: docker-tag-push
        vars:
          IMAGE: sonr-node
          REGISTRY: ghcr.io/sonrhq
# ------------------------------------------------------------------------------
# -- Internal Tasks ------------------------------------------------------------
# ------------------------------------------------------------------------------
  docker-tag-push:
    silent: true
    internal: true
    desc: Build, tag and push the docker image
    cmds:
      - docker build -f ./Dockerfile . --no-cache --target {{.IMAGE}} -t {{.IMAGE}}
      - docker tag {{.IMAGE}} {{.REGISTRY}}/{{.IMAGE}}:latest
      - docker tag {{.IMAGE}} {{.REGISTRY}}/{{.IMAGE}}:{{.VERSION}}
      - docker tag {{.IMAGE}} {{.REGISTRY}}/{{.IMAGE}}:{{.COMMIT}}
      - docker push {{.REGISTRY}}/{{.IMAGE}}:latest
      - docker push {{.REGISTRY}}/{{.IMAGE}}:{{.VERSION}}
      - docker push {{.REGISTRY}}/{{.IMAGE}}:{{.COMMIT}}
    requires:
      vars: [IMAGE, REGISTRY]

  go-build:
    silent: true
    internal: true
    desc: Build the go binary
    cmds:
      - mkdir -p ./build/sonrd-{{.OS}}-{{.ARCH}}
      - GOOS={{.OS}} GOARCH={{.ARCH}} go build -o ./build/sonrd-{{.OS}}-{{.ARCH}}/sonrd ./cmd/sonrd
      - cp ./scripts ./build/sonrd-{{.OS}}-{{.ARCH}}/scripts -p
    requires:
      vars: [OS,ARCH]
