version: "3"
dir: ../
env:
  ENV: development

# -----------------------------------------------------------------------------
# -- Project Config ------------------------------------------------------------
# -----------------------------------------------------------------------------
vars:
  VERSION:
    sh: echo $(git describe --tags --abbrev=0)
    default: "v0.0.0"
  COMMIT:
    sh: git log -n 1 --format=%h
    default: "0000000"
  DATE:
    sh: date -u '+%m/%d/%y %I:%M:%S%p'
    default: "1970-01-01_00:00:00AM"

# ----------------------------------------------------------------------------
# -- Public Tasks ------------------------------------------------------------
# ----------------------------------------------------------------------------
tasks:
  default:
    desc: Serve the blockchain locally with verbose logging
    cmds:
      - docker compose up

  generate:
    desc: Generate the protobuf files
    cmds:
      - sh ./scripts/generate.sh
