version: 1
build:
  main: cmd/sonrd
  binary: sonrd
  proto:
    path: ""
    third_party_paths: []
accounts:
- name: rome
  coins:
  - 0snr
  - 10000000000000000000000000usnr
- name: niagra
  coins:
  - 100000snr
  - 10000000000000000000000000usnr
faucet:
  name: niagra
  coins:
  - 50000snr
  - 100000000usnr
genesis:
  app_state:
    mint:
      minter:
        annual_provisions: "0.000000"
        inflation: "0.050000"
      params:
        goal_bonded: "0.550000"
        inflation_max: "0.075000"
        inflation_min: "0.025000"
        inflation_rate_change: "0.025000"
        mint_denom: usnr
    staking:
      params:
        bond_denom: usnr
        max_validators: 64
validators:
- name: rome
  bonded: 1000000000usnr
  app:
    pruning: nothing
  config:
    moniker: sonr-testnet-0
  client:
    output: json
