version: 1
build:
  main: cmd/sonrd
  binary: sonrd
  proto:
    path: ""
    third_party_paths: []
accounts:
- name: alice
  coins:
  - 2000000000snr
  - 200000000stake
- name: bob
  coins:
  - 1000000000snr
  - 100000000stake
faucet:
  name: bob
  coins:
  - 50000000snr
  - 100000000stake
genesis:
  app_state:
    staking:
      params:
        bond_denom: stake
validators:
- name: alice
  bonded: 100000000stake
  app:
    pruning: nothing
  config:
    moniker: florence
  client:
    output: json
  home: ~/.sonr
