version: "3"
dotenv: [".env", "{{.ENV}}/.env.", "{{.HOME}}/.env"]

vars:
  VERSION:
    sh: echo $(git describe --tags --abbrev=0)
    default: "v0.0.0"
  COMMIT:
    sh: git log -n 1 --format=%h
    default: "0000000"
  DATE:
    sh: date -u '+%m/%d/%y %I:%M:%S%p'
    default: "1970-01-01_00:00:00AM"

includes:
  build:
    taskfile: .taskfiles/Build.yml
  dev:
    taskfile: .taskfiles/Dev.yml
  sonr:
    taskfile: .taskfiles/Sonr.yml


# ----------------------------------------------------------------------------
# -- Public Tasks ------------------------------------------------------------
# ----------------------------------------------------------------------------
tasks:
  default:
    desc: Print the version
    silent: true
    cmds:
      - echo -----------------------------------------------
      - echo '(sonrhq/core) - https://github.com/sonrhq/core'
      - echo -----------------------------------------------
      - echo "{{.VERSION}}   |  {{.COMMIT}}  |   {{.DATE}}"
      - task -l

  db:
    desc: Install the database
    cmds:
      - git clone https://github.com/sonrhq/icefire.git .tmp/icefire
