// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: protocol/vault/v1/authentication.proto

// Package Motor is used for defining a Motor node and its properties.

package v1

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/sonrhq/core/x/identity/types"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// RegisterStartRequest is the request to register a new account.
type RegisterStartRequest struct {
	Origin            string `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	DeviceLabel       string `protobuf:"bytes,2,opt,name=device_label,json=deviceLabel,proto3" json:"device_label,omitempty"`
	SecurityThreshold int32  `protobuf:"varint,3,opt,name=security_threshold,json=securityThreshold,proto3" json:"security_threshold,omitempty"`
	Passcode          []byte `protobuf:"bytes,4,opt,name=passcode,proto3" json:"passcode,omitempty"`
}

func (m *RegisterStartRequest) Reset()         { *m = RegisterStartRequest{} }
func (m *RegisterStartRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterStartRequest) ProtoMessage()    {}
func (*RegisterStartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c447484e73442ef8, []int{0}
}
func (m *RegisterStartRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RegisterStartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RegisterStartRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RegisterStartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterStartRequest.Merge(m, src)
}
func (m *RegisterStartRequest) XXX_Size() int {
	return m.Size()
}
func (m *RegisterStartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterStartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterStartRequest proto.InternalMessageInfo

func (m *RegisterStartRequest) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *RegisterStartRequest) GetDeviceLabel() string {
	if m != nil {
		return m.DeviceLabel
	}
	return ""
}

func (m *RegisterStartRequest) GetSecurityThreshold() int32 {
	if m != nil {
		return m.SecurityThreshold
	}
	return 0
}

func (m *RegisterStartRequest) GetPasscode() []byte {
	if m != nil {
		return m.Passcode
	}
	return nil
}

// RegisterStartResponse is the response to a Register request.
type RegisterStartResponse struct {
	AccountAddress  string `protobuf:"bytes,1,opt,name=account_address,json=accountAddress,proto3" json:"account_address,omitempty"`
	Aka             string `protobuf:"bytes,2,opt,name=aka,proto3" json:"aka,omitempty"`
	CreationOptions string `protobuf:"bytes,3,opt,name=creation_options,json=creationOptions,proto3" json:"creation_options,omitempty"`
	SessionId       string `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
}

func (m *RegisterStartResponse) Reset()         { *m = RegisterStartResponse{} }
func (m *RegisterStartResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterStartResponse) ProtoMessage()    {}
func (*RegisterStartResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c447484e73442ef8, []int{1}
}
func (m *RegisterStartResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RegisterStartResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RegisterStartResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RegisterStartResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterStartResponse.Merge(m, src)
}
func (m *RegisterStartResponse) XXX_Size() int {
	return m.Size()
}
func (m *RegisterStartResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterStartResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterStartResponse proto.InternalMessageInfo

func (m *RegisterStartResponse) GetAccountAddress() string {
	if m != nil {
		return m.AccountAddress
	}
	return ""
}

func (m *RegisterStartResponse) GetAka() string {
	if m != nil {
		return m.Aka
	}
	return ""
}

func (m *RegisterStartResponse) GetCreationOptions() string {
	if m != nil {
		return m.CreationOptions
	}
	return ""
}

func (m *RegisterStartResponse) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

// RegisterFinishRequest is the request to CreateAccount a new key from the private key.
type RegisterFinishRequest struct {
	SessionId          string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	CredentialResponse string `protobuf:"bytes,2,opt,name=credential_response,json=credentialResponse,proto3" json:"credential_response,omitempty"`
}

func (m *RegisterFinishRequest) Reset()         { *m = RegisterFinishRequest{} }
func (m *RegisterFinishRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterFinishRequest) ProtoMessage()    {}
func (*RegisterFinishRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c447484e73442ef8, []int{2}
}
func (m *RegisterFinishRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RegisterFinishRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RegisterFinishRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RegisterFinishRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterFinishRequest.Merge(m, src)
}
func (m *RegisterFinishRequest) XXX_Size() int {
	return m.Size()
}
func (m *RegisterFinishRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterFinishRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterFinishRequest proto.InternalMessageInfo

func (m *RegisterFinishRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *RegisterFinishRequest) GetCredentialResponse() string {
	if m != nil {
		return m.CredentialResponse
	}
	return ""
}

// RegisterFinishResponse is the response to a CreateAccount request.
type RegisterFinishResponse struct {
	Id              []byte             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address         string             `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	DidDocument     *types.DidDocument `protobuf:"bytes,3,opt,name=did_document,json=didDocument,proto3" json:"did_document,omitempty"`
	AccountInfo     *AccountInfo       `protobuf:"bytes,4,opt,name=account_info,json=accountInfo,proto3" json:"account_info,omitempty"`
	UcanTokenHeader []byte             `protobuf:"bytes,5,opt,name=ucan_token_header,json=ucanTokenHeader,proto3" json:"ucan_token_header,omitempty"`
}

func (m *RegisterFinishResponse) Reset()         { *m = RegisterFinishResponse{} }
func (m *RegisterFinishResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterFinishResponse) ProtoMessage()    {}
func (*RegisterFinishResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c447484e73442ef8, []int{3}
}
func (m *RegisterFinishResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RegisterFinishResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RegisterFinishResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RegisterFinishResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterFinishResponse.Merge(m, src)
}
func (m *RegisterFinishResponse) XXX_Size() int {
	return m.Size()
}
func (m *RegisterFinishResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterFinishResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterFinishResponse proto.InternalMessageInfo

func (m *RegisterFinishResponse) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *RegisterFinishResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *RegisterFinishResponse) GetDidDocument() *types.DidDocument {
	if m != nil {
		return m.DidDocument
	}
	return nil
}

func (m *RegisterFinishResponse) GetAccountInfo() *AccountInfo {
	if m != nil {
		return m.AccountInfo
	}
	return nil
}

func (m *RegisterFinishResponse) GetUcanTokenHeader() []byte {
	if m != nil {
		return m.UcanTokenHeader
	}
	return nil
}

// LoginStartRequest is the request to login to an account.
type LoginStartRequest struct {
	Origin         string `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	AccountAddress string `protobuf:"bytes,2,opt,name=account_address,json=accountAddress,proto3" json:"account_address,omitempty"`
}

func (m *LoginStartRequest) Reset()         { *m = LoginStartRequest{} }
func (m *LoginStartRequest) String() string { return proto.CompactTextString(m) }
func (*LoginStartRequest) ProtoMessage()    {}
func (*LoginStartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c447484e73442ef8, []int{4}
}
func (m *LoginStartRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LoginStartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LoginStartRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LoginStartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginStartRequest.Merge(m, src)
}
func (m *LoginStartRequest) XXX_Size() int {
	return m.Size()
}
func (m *LoginStartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginStartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginStartRequest proto.InternalMessageInfo

func (m *LoginStartRequest) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *LoginStartRequest) GetAccountAddress() string {
	if m != nil {
		return m.AccountAddress
	}
	return ""
}

// LoginStartResponse is the response to a Login request.
type LoginStartResponse struct {
	Success           bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	AccountAddress    string `protobuf:"bytes,2,opt,name=account_address,json=accountAddress,proto3" json:"account_address,omitempty"`
	Aka               string `protobuf:"bytes,3,opt,name=aka,proto3" json:"aka,omitempty"`
	CredentialOptions string `protobuf:"bytes,4,opt,name=credential_options,json=credentialOptions,proto3" json:"credential_options,omitempty"`
}

func (m *LoginStartResponse) Reset()         { *m = LoginStartResponse{} }
func (m *LoginStartResponse) String() string { return proto.CompactTextString(m) }
func (*LoginStartResponse) ProtoMessage()    {}
func (*LoginStartResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c447484e73442ef8, []int{5}
}
func (m *LoginStartResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LoginStartResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LoginStartResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LoginStartResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginStartResponse.Merge(m, src)
}
func (m *LoginStartResponse) XXX_Size() int {
	return m.Size()
}
func (m *LoginStartResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginStartResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginStartResponse proto.InternalMessageInfo

func (m *LoginStartResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *LoginStartResponse) GetAccountAddress() string {
	if m != nil {
		return m.AccountAddress
	}
	return ""
}

func (m *LoginStartResponse) GetAka() string {
	if m != nil {
		return m.Aka
	}
	return ""
}

func (m *LoginStartResponse) GetCredentialOptions() string {
	if m != nil {
		return m.CredentialOptions
	}
	return ""
}

// LoginFinishRequest is the request to login to an account.
type LoginFinishRequest struct {
	AccountAddress     string `protobuf:"bytes,1,opt,name=account_address,json=accountAddress,proto3" json:"account_address,omitempty"`
	CredentialResponse string `protobuf:"bytes,2,opt,name=credential_response,json=credentialResponse,proto3" json:"credential_response,omitempty"`
}

func (m *LoginFinishRequest) Reset()         { *m = LoginFinishRequest{} }
func (m *LoginFinishRequest) String() string { return proto.CompactTextString(m) }
func (*LoginFinishRequest) ProtoMessage()    {}
func (*LoginFinishRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c447484e73442ef8, []int{6}
}
func (m *LoginFinishRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LoginFinishRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LoginFinishRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LoginFinishRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginFinishRequest.Merge(m, src)
}
func (m *LoginFinishRequest) XXX_Size() int {
	return m.Size()
}
func (m *LoginFinishRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginFinishRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginFinishRequest proto.InternalMessageInfo

func (m *LoginFinishRequest) GetAccountAddress() string {
	if m != nil {
		return m.AccountAddress
	}
	return ""
}

func (m *LoginFinishRequest) GetCredentialResponse() string {
	if m != nil {
		return m.CredentialResponse
	}
	return ""
}

// LoginFinishResponse is the response to a Login request.
type LoginFinishResponse struct {
	Success         bool               `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	AccountAddress  string             `protobuf:"bytes,2,opt,name=account_address,json=accountAddress,proto3" json:"account_address,omitempty"`
	DidDocument     *types.DidDocument `protobuf:"bytes,3,opt,name=did_document,json=didDocument,proto3" json:"did_document,omitempty"`
	AccountInfo     *AccountInfo       `protobuf:"bytes,4,opt,name=account_info,json=accountInfo,proto3" json:"account_info,omitempty"`
	UcanTokenHeader []byte             `protobuf:"bytes,5,opt,name=ucan_token_header,json=ucanTokenHeader,proto3" json:"ucan_token_header,omitempty"`
}

func (m *LoginFinishResponse) Reset()         { *m = LoginFinishResponse{} }
func (m *LoginFinishResponse) String() string { return proto.CompactTextString(m) }
func (*LoginFinishResponse) ProtoMessage()    {}
func (*LoginFinishResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c447484e73442ef8, []int{7}
}
func (m *LoginFinishResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LoginFinishResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LoginFinishResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LoginFinishResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginFinishResponse.Merge(m, src)
}
func (m *LoginFinishResponse) XXX_Size() int {
	return m.Size()
}
func (m *LoginFinishResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginFinishResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginFinishResponse proto.InternalMessageInfo

func (m *LoginFinishResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *LoginFinishResponse) GetAccountAddress() string {
	if m != nil {
		return m.AccountAddress
	}
	return ""
}

func (m *LoginFinishResponse) GetDidDocument() *types.DidDocument {
	if m != nil {
		return m.DidDocument
	}
	return nil
}

func (m *LoginFinishResponse) GetAccountInfo() *AccountInfo {
	if m != nil {
		return m.AccountInfo
	}
	return nil
}

func (m *LoginFinishResponse) GetUcanTokenHeader() []byte {
	if m != nil {
		return m.UcanTokenHeader
	}
	return nil
}

func init() {
	proto.RegisterType((*RegisterStartRequest)(nil), "sonrhq.protocol.vault.v1.RegisterStartRequest")
	proto.RegisterType((*RegisterStartResponse)(nil), "sonrhq.protocol.vault.v1.RegisterStartResponse")
	proto.RegisterType((*RegisterFinishRequest)(nil), "sonrhq.protocol.vault.v1.RegisterFinishRequest")
	proto.RegisterType((*RegisterFinishResponse)(nil), "sonrhq.protocol.vault.v1.RegisterFinishResponse")
	proto.RegisterType((*LoginStartRequest)(nil), "sonrhq.protocol.vault.v1.LoginStartRequest")
	proto.RegisterType((*LoginStartResponse)(nil), "sonrhq.protocol.vault.v1.LoginStartResponse")
	proto.RegisterType((*LoginFinishRequest)(nil), "sonrhq.protocol.vault.v1.LoginFinishRequest")
	proto.RegisterType((*LoginFinishResponse)(nil), "sonrhq.protocol.vault.v1.LoginFinishResponse")
}

func init() {
	proto.RegisterFile("protocol/vault/v1/authentication.proto", fileDescriptor_c447484e73442ef8)
}

var fileDescriptor_c447484e73442ef8 = []byte{
	// 784 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x96, 0xcf, 0x4f, 0xdc, 0x38,
	0x14, 0xc7, 0xc9, 0xb0, 0xfc, 0x18, 0xcf, 0x2c, 0x30, 0x66, 0x17, 0x45, 0x23, 0x98, 0x1d, 0x22,
	0x58, 0x66, 0x61, 0x49, 0x80, 0xbd, 0xed, 0x8d, 0x15, 0xda, 0x85, 0x15, 0x52, 0xa5, 0x14, 0xf5,
	0xd0, 0x4b, 0x64, 0x62, 0x33, 0x63, 0x11, 0xec, 0x21, 0x76, 0x46, 0xe5, 0x48, 0xff, 0x02, 0xa4,
	0x56, 0x6a, 0x0f, 0x1c, 0xfa, 0xe7, 0xf4, 0x88, 0xd4, 0x4b, 0x8f, 0x15, 0xf4, 0x0f, 0xa9, 0xec,
	0x38, 0x84, 0x00, 0xa3, 0xa6, 0x52, 0x2f, 0xbd, 0x8d, 0xdf, 0x7b, 0x7e, 0xef, 0xe3, 0xaf, 0xbf,
	0xf2, 0x04, 0xfc, 0xde, 0x8f, 0xb9, 0xe4, 0x21, 0x8f, 0xbc, 0x01, 0x4a, 0x22, 0xe9, 0x0d, 0x36,
	0x3d, 0x94, 0xc8, 0x1e, 0x61, 0x92, 0x86, 0x48, 0x52, 0xce, 0x5c, 0x5d, 0x00, 0x6d, 0xc1, 0x59,
	0xdc, 0x3b, 0x75, 0xb3, 0x72, 0x57, 0x97, 0xbb, 0x83, 0xcd, 0x66, 0x33, 0xe4, 0x31, 0xf1, 0x28,
	0x56, 0x5b, 0xe4, 0x99, 0x6a, 0x80, 0x29, 0x4e, 0xeb, 0x9a, 0xf3, 0x5d, 0xce, 0xbb, 0x11, 0xf1,
	0x50, 0x9f, 0x7a, 0x88, 0x31, 0x2e, 0x75, 0x4b, 0x61, 0xb2, 0xad, 0x87, 0xb3, 0x4f, 0x38, 0x26,
	0x91, 0xc9, 0x3b, 0x97, 0x16, 0xf8, 0xc5, 0x27, 0x5d, 0x2a, 0x24, 0x89, 0x9f, 0x4a, 0x14, 0x4b,
	0x9f, 0x9c, 0x26, 0x44, 0x48, 0x38, 0x07, 0xc6, 0x79, 0x4c, 0xbb, 0x94, 0xd9, 0x56, 0xdb, 0xea,
	0x54, 0x7d, 0xb3, 0x82, 0x8b, 0xa0, 0x8e, 0xc9, 0x80, 0x86, 0x24, 0x88, 0xd0, 0x21, 0x89, 0xec,
	0x8a, 0xce, 0xd6, 0xd2, 0xd8, 0xbe, 0x0a, 0xc1, 0x75, 0x00, 0x05, 0x09, 0x93, 0x98, 0xca, 0xb3,
	0x40, 0xf6, 0x62, 0x22, 0x7a, 0x3c, 0xc2, 0xf6, 0x68, 0xdb, 0xea, 0x8c, 0xf9, 0x8d, 0x2c, 0x73,
	0x90, 0x25, 0x60, 0x13, 0x4c, 0xf6, 0x91, 0x10, 0x21, 0xc7, 0xc4, 0xfe, 0xa9, 0x6d, 0x75, 0xea,
	0xfe, 0xed, 0x5a, 0xe1, 0xfd, 0x7a, 0x0f, 0x4f, 0xf4, 0x39, 0x13, 0x04, 0xae, 0x80, 0x69, 0x14,
	0x86, 0x3c, 0x61, 0x32, 0x40, 0x18, 0xc7, 0x44, 0x08, 0x03, 0x3a, 0x65, 0xc2, 0xdb, 0x69, 0x14,
	0xce, 0x80, 0x51, 0x74, 0x8c, 0x0c, 0xa7, 0xfa, 0x09, 0xff, 0x00, 0x33, 0x61, 0x4c, 0xb4, 0x4c,
	0x01, 0xef, 0x6b, 0xb5, 0x34, 0x5d, 0xd5, 0x9f, 0xce, 0xe2, 0x4f, 0xd2, 0x30, 0x5c, 0x00, 0x40,
	0x10, 0x21, 0x54, 0x25, 0xc5, 0x9a, 0xae, 0xea, 0x57, 0x4d, 0x64, 0x0f, 0x3b, 0xdd, 0x9c, 0xee,
	0x5f, 0xca, 0xa8, 0xe8, 0x65, 0xea, 0x15, 0xf7, 0x59, 0xf7, 0xf6, 0x41, 0x0f, 0xcc, 0x86, 0x31,
	0xd1, 0xd7, 0x89, 0xa2, 0x20, 0x36, 0x67, 0x32, 0x8c, 0x30, 0x4f, 0x65, 0xa7, 0x75, 0xce, 0x2b,
	0x60, 0xee, 0xfe, 0x24, 0x23, 0xc4, 0x14, 0xa8, 0x98, 0x11, 0x75, 0xbf, 0x42, 0x31, 0xb4, 0xc1,
	0x44, 0x26, 0x48, 0xda, 0x2f, 0x5b, 0xc2, 0xff, 0x40, 0x1d, 0x53, 0x1c, 0x60, 0x1e, 0x26, 0x27,
	0x84, 0x49, 0x7d, 0xe6, 0xda, 0xd6, 0x92, 0x6b, 0x6c, 0xa7, 0x3c, 0xe6, 0x66, 0x1e, 0x73, 0x07,
	0x9b, 0xee, 0x0e, 0xc5, 0x3b, 0xa6, 0xd6, 0xaf, 0xe1, 0x7c, 0x01, 0x77, 0x41, 0x3d, 0xd3, 0x9e,
	0xb2, 0x23, 0xae, 0x75, 0xa9, 0x6d, 0x2d, 0xbb, 0xc3, 0xfc, 0xeb, 0x6e, 0xa7, 0xd5, 0x7b, 0xec,
	0x88, 0xfb, 0x35, 0x94, 0x2f, 0xe0, 0x2a, 0x68, 0x24, 0x21, 0x62, 0x81, 0xe4, 0xc7, 0x84, 0x05,
	0x3d, 0x82, 0x30, 0x89, 0xed, 0x31, 0x7d, 0x96, 0x69, 0x95, 0x38, 0x50, 0xf1, 0x5d, 0x1d, 0x76,
	0x0e, 0x40, 0x63, 0x9f, 0x77, 0x29, 0x2b, 0x65, 0xd3, 0x47, 0xec, 0x51, 0x79, 0xcc, 0x1e, 0xce,
	0x5b, 0x0b, 0xc0, 0xbb, 0x6d, 0x8d, 0xaa, 0x36, 0x98, 0x10, 0x49, 0x18, 0x66, 0xb6, 0x9a, 0xf4,
	0xb3, 0x65, 0xe9, 0xce, 0x99, 0xf1, 0x46, 0x73, 0xe3, 0xad, 0x83, 0x3b, 0x77, 0x7b, 0x6b, 0xbd,
	0xd4, 0x55, 0x8d, 0x3c, 0x63, 0xcc, 0xe7, 0x30, 0x43, 0x56, 0xb4, 0x56, 0x69, 0xe3, 0x7f, 0xb3,
	0xc9, 0xde, 0x54, 0xc0, 0x6c, 0x61, 0xe0, 0xf7, 0xd3, 0xe2, 0xc7, 0xb6, 0xde, 0xd6, 0xf9, 0x18,
	0x98, 0x7d, 0xa6, 0x3a, 0x6e, 0x17, 0xde, 0x6d, 0x78, 0x61, 0x01, 0x90, 0x9b, 0x07, 0xae, 0x0d,
	0xc7, 0x78, 0xe0, 0xdc, 0xe6, 0x9f, 0xe5, 0x8a, 0xcd, 0xdd, 0xac, 0xbc, 0xfc, 0xf0, 0xf9, 0x55,
	0x65, 0xf1, 0x6f, 0x6b, 0xd5, 0x99, 0xf7, 0xd4, 0x46, 0xf3, 0x9e, 0xab, 0x3f, 0x12, 0x2f, 0x52,
	0xf5, 0x9e, 0xd0, 0x0c, 0xaf, 0x2d, 0x50, 0xbb, 0x73, 0x89, 0xf0, 0x6b, 0x63, 0x0a, 0xe6, 0x6a,
	0xae, 0x97, 0xac, 0x36, 0x54, 0x1d, 0x4d, 0xe5, 0x28, 0xaa, 0x85, 0x21, 0x54, 0x47, 0x29, 0xc6,
	0xa5, 0x05, 0x7e, 0x2e, 0x3c, 0xe4, 0xd0, 0x1d, 0x3e, 0xea, 0xb1, 0x3f, 0xa4, 0xa6, 0x57, 0xba,
	0xde, 0xc0, 0xad, 0x6a, 0xb8, 0x25, 0x05, 0xf7, 0xdb, 0x03, 0xb8, 0xd8, 0x6c, 0x31, 0xaa, 0xbd,
	0xb3, 0xc0, 0x54, 0xf1, 0x7d, 0x85, 0x25, 0xe6, 0x15, 0xb5, 0xdb, 0x28, 0xbf, 0xc1, 0x10, 0xae,
	0x69, 0xc2, 0x65, 0x45, 0xd8, 0x1e, 0x4e, 0x98, 0x2a, 0xf8, 0xcf, 0xff, 0xef, 0xaf, 0x5b, 0xd6,
	0xd5, 0x75, 0xcb, 0xfa, 0x74, 0xdd, 0xb2, 0x2e, 0x6e, 0x5a, 0x23, 0x57, 0x37, 0xad, 0x91, 0x8f,
	0x37, 0xad, 0x91, 0xe7, 0x1b, 0x5d, 0x2a, 0x7b, 0xc9, 0xa1, 0x1b, 0xf2, 0x13, 0x2f, 0x45, 0xf0,
	0xf4, 0xf7, 0xc2, 0x8b, 0xfc, 0x8b, 0x41, 0x9e, 0xf5, 0x89, 0xb8, 0xfd, 0x04, 0x38, 0x1c, 0xd7,
	0x88, 0x7f, 0x7d, 0x09, 0x00, 0x00, 0xff, 0xff, 0x82, 0x7a, 0x1e, 0x73, 0x9a, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VaultAuthenticationClient is the client API for VaultAuthentication service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VaultAuthenticationClient interface {
	// LoginStart starts the login process and returns the credential options.
	LoginStart(ctx context.Context, in *LoginStartRequest, opts ...grpc.CallOption) (*LoginStartResponse, error)
	// LoginFinish finishes the login process and returns the account info.
	LoginFinish(ctx context.Context, in *LoginFinishRequest, opts ...grpc.CallOption) (*LoginFinishResponse, error)
	// RegisterStart creates a new Webauthn credential and returns it.
	RegisterStart(ctx context.Context, in *RegisterStartRequest, opts ...grpc.CallOption) (*RegisterStartResponse, error)
	// RegisterFinish creates a new Bip32 child key and returns the configuration.
	RegisterFinish(ctx context.Context, in *RegisterFinishRequest, opts ...grpc.CallOption) (*RegisterFinishResponse, error)
}

type vaultAuthenticationClient struct {
	cc grpc1.ClientConn
}

func NewVaultAuthenticationClient(cc grpc1.ClientConn) VaultAuthenticationClient {
	return &vaultAuthenticationClient{cc}
}

func (c *vaultAuthenticationClient) LoginStart(ctx context.Context, in *LoginStartRequest, opts ...grpc.CallOption) (*LoginStartResponse, error) {
	out := new(LoginStartResponse)
	err := c.cc.Invoke(ctx, "/sonrhq.protocol.vault.v1.VaultAuthentication/LoginStart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaultAuthenticationClient) LoginFinish(ctx context.Context, in *LoginFinishRequest, opts ...grpc.CallOption) (*LoginFinishResponse, error) {
	out := new(LoginFinishResponse)
	err := c.cc.Invoke(ctx, "/sonrhq.protocol.vault.v1.VaultAuthentication/LoginFinish", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaultAuthenticationClient) RegisterStart(ctx context.Context, in *RegisterStartRequest, opts ...grpc.CallOption) (*RegisterStartResponse, error) {
	out := new(RegisterStartResponse)
	err := c.cc.Invoke(ctx, "/sonrhq.protocol.vault.v1.VaultAuthentication/RegisterStart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaultAuthenticationClient) RegisterFinish(ctx context.Context, in *RegisterFinishRequest, opts ...grpc.CallOption) (*RegisterFinishResponse, error) {
	out := new(RegisterFinishResponse)
	err := c.cc.Invoke(ctx, "/sonrhq.protocol.vault.v1.VaultAuthentication/RegisterFinish", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VaultAuthenticationServer is the server API for VaultAuthentication service.
type VaultAuthenticationServer interface {
	// LoginStart starts the login process and returns the credential options.
	LoginStart(context.Context, *LoginStartRequest) (*LoginStartResponse, error)
	// LoginFinish finishes the login process and returns the account info.
	LoginFinish(context.Context, *LoginFinishRequest) (*LoginFinishResponse, error)
	// RegisterStart creates a new Webauthn credential and returns it.
	RegisterStart(context.Context, *RegisterStartRequest) (*RegisterStartResponse, error)
	// RegisterFinish creates a new Bip32 child key and returns the configuration.
	RegisterFinish(context.Context, *RegisterFinishRequest) (*RegisterFinishResponse, error)
}

// UnimplementedVaultAuthenticationServer can be embedded to have forward compatible implementations.
type UnimplementedVaultAuthenticationServer struct {
}

func (*UnimplementedVaultAuthenticationServer) LoginStart(ctx context.Context, req *LoginStartRequest) (*LoginStartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginStart not implemented")
}
func (*UnimplementedVaultAuthenticationServer) LoginFinish(ctx context.Context, req *LoginFinishRequest) (*LoginFinishResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginFinish not implemented")
}
func (*UnimplementedVaultAuthenticationServer) RegisterStart(ctx context.Context, req *RegisterStartRequest) (*RegisterStartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterStart not implemented")
}
func (*UnimplementedVaultAuthenticationServer) RegisterFinish(ctx context.Context, req *RegisterFinishRequest) (*RegisterFinishResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterFinish not implemented")
}

func RegisterVaultAuthenticationServer(s grpc1.Server, srv VaultAuthenticationServer) {
	s.RegisterService(&_VaultAuthentication_serviceDesc, srv)
}

func _VaultAuthentication_LoginStart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginStartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaultAuthenticationServer).LoginStart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonrhq.protocol.vault.v1.VaultAuthentication/LoginStart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaultAuthenticationServer).LoginStart(ctx, req.(*LoginStartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaultAuthentication_LoginFinish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginFinishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaultAuthenticationServer).LoginFinish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonrhq.protocol.vault.v1.VaultAuthentication/LoginFinish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaultAuthenticationServer).LoginFinish(ctx, req.(*LoginFinishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaultAuthentication_RegisterStart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterStartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaultAuthenticationServer).RegisterStart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonrhq.protocol.vault.v1.VaultAuthentication/RegisterStart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaultAuthenticationServer).RegisterStart(ctx, req.(*RegisterStartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaultAuthentication_RegisterFinish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterFinishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaultAuthenticationServer).RegisterFinish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sonrhq.protocol.vault.v1.VaultAuthentication/RegisterFinish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaultAuthenticationServer).RegisterFinish(ctx, req.(*RegisterFinishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VaultAuthentication_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sonrhq.protocol.vault.v1.VaultAuthentication",
	HandlerType: (*VaultAuthenticationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoginStart",
			Handler:    _VaultAuthentication_LoginStart_Handler,
		},
		{
			MethodName: "LoginFinish",
			Handler:    _VaultAuthentication_LoginFinish_Handler,
		},
		{
			MethodName: "RegisterStart",
			Handler:    _VaultAuthentication_RegisterStart_Handler,
		},
		{
			MethodName: "RegisterFinish",
			Handler:    _VaultAuthentication_RegisterFinish_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protocol/vault/v1/authentication.proto",
}

func (m *RegisterStartRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RegisterStartRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RegisterStartRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Passcode) > 0 {
		i -= len(m.Passcode)
		copy(dAtA[i:], m.Passcode)
		i = encodeVarintAuthentication(dAtA, i, uint64(len(m.Passcode)))
		i--
		dAtA[i] = 0x22
	}
	if m.SecurityThreshold != 0 {
		i = encodeVarintAuthentication(dAtA, i, uint64(m.SecurityThreshold))
		i--
		dAtA[i] = 0x18
	}
	if len(m.DeviceLabel) > 0 {
		i -= len(m.DeviceLabel)
		copy(dAtA[i:], m.DeviceLabel)
		i = encodeVarintAuthentication(dAtA, i, uint64(len(m.DeviceLabel)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Origin) > 0 {
		i -= len(m.Origin)
		copy(dAtA[i:], m.Origin)
		i = encodeVarintAuthentication(dAtA, i, uint64(len(m.Origin)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RegisterStartResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RegisterStartResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RegisterStartResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SessionId) > 0 {
		i -= len(m.SessionId)
		copy(dAtA[i:], m.SessionId)
		i = encodeVarintAuthentication(dAtA, i, uint64(len(m.SessionId)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.CreationOptions) > 0 {
		i -= len(m.CreationOptions)
		copy(dAtA[i:], m.CreationOptions)
		i = encodeVarintAuthentication(dAtA, i, uint64(len(m.CreationOptions)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Aka) > 0 {
		i -= len(m.Aka)
		copy(dAtA[i:], m.Aka)
		i = encodeVarintAuthentication(dAtA, i, uint64(len(m.Aka)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.AccountAddress) > 0 {
		i -= len(m.AccountAddress)
		copy(dAtA[i:], m.AccountAddress)
		i = encodeVarintAuthentication(dAtA, i, uint64(len(m.AccountAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RegisterFinishRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RegisterFinishRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RegisterFinishRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CredentialResponse) > 0 {
		i -= len(m.CredentialResponse)
		copy(dAtA[i:], m.CredentialResponse)
		i = encodeVarintAuthentication(dAtA, i, uint64(len(m.CredentialResponse)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.SessionId) > 0 {
		i -= len(m.SessionId)
		copy(dAtA[i:], m.SessionId)
		i = encodeVarintAuthentication(dAtA, i, uint64(len(m.SessionId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RegisterFinishResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RegisterFinishResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RegisterFinishResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.UcanTokenHeader) > 0 {
		i -= len(m.UcanTokenHeader)
		copy(dAtA[i:], m.UcanTokenHeader)
		i = encodeVarintAuthentication(dAtA, i, uint64(len(m.UcanTokenHeader)))
		i--
		dAtA[i] = 0x2a
	}
	if m.AccountInfo != nil {
		{
			size, err := m.AccountInfo.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAuthentication(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.DidDocument != nil {
		{
			size, err := m.DidDocument.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAuthentication(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintAuthentication(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintAuthentication(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *LoginStartRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LoginStartRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LoginStartRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AccountAddress) > 0 {
		i -= len(m.AccountAddress)
		copy(dAtA[i:], m.AccountAddress)
		i = encodeVarintAuthentication(dAtA, i, uint64(len(m.AccountAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Origin) > 0 {
		i -= len(m.Origin)
		copy(dAtA[i:], m.Origin)
		i = encodeVarintAuthentication(dAtA, i, uint64(len(m.Origin)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *LoginStartResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LoginStartResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LoginStartResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CredentialOptions) > 0 {
		i -= len(m.CredentialOptions)
		copy(dAtA[i:], m.CredentialOptions)
		i = encodeVarintAuthentication(dAtA, i, uint64(len(m.CredentialOptions)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Aka) > 0 {
		i -= len(m.Aka)
		copy(dAtA[i:], m.Aka)
		i = encodeVarintAuthentication(dAtA, i, uint64(len(m.Aka)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.AccountAddress) > 0 {
		i -= len(m.AccountAddress)
		copy(dAtA[i:], m.AccountAddress)
		i = encodeVarintAuthentication(dAtA, i, uint64(len(m.AccountAddress)))
		i--
		dAtA[i] = 0x12
	}
	if m.Success {
		i--
		if m.Success {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *LoginFinishRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LoginFinishRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LoginFinishRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CredentialResponse) > 0 {
		i -= len(m.CredentialResponse)
		copy(dAtA[i:], m.CredentialResponse)
		i = encodeVarintAuthentication(dAtA, i, uint64(len(m.CredentialResponse)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.AccountAddress) > 0 {
		i -= len(m.AccountAddress)
		copy(dAtA[i:], m.AccountAddress)
		i = encodeVarintAuthentication(dAtA, i, uint64(len(m.AccountAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *LoginFinishResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LoginFinishResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LoginFinishResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.UcanTokenHeader) > 0 {
		i -= len(m.UcanTokenHeader)
		copy(dAtA[i:], m.UcanTokenHeader)
		i = encodeVarintAuthentication(dAtA, i, uint64(len(m.UcanTokenHeader)))
		i--
		dAtA[i] = 0x2a
	}
	if m.AccountInfo != nil {
		{
			size, err := m.AccountInfo.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAuthentication(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.DidDocument != nil {
		{
			size, err := m.DidDocument.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAuthentication(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.AccountAddress) > 0 {
		i -= len(m.AccountAddress)
		copy(dAtA[i:], m.AccountAddress)
		i = encodeVarintAuthentication(dAtA, i, uint64(len(m.AccountAddress)))
		i--
		dAtA[i] = 0x12
	}
	if m.Success {
		i--
		if m.Success {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintAuthentication(dAtA []byte, offset int, v uint64) int {
	offset -= sovAuthentication(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *RegisterStartRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Origin)
	if l > 0 {
		n += 1 + l + sovAuthentication(uint64(l))
	}
	l = len(m.DeviceLabel)
	if l > 0 {
		n += 1 + l + sovAuthentication(uint64(l))
	}
	if m.SecurityThreshold != 0 {
		n += 1 + sovAuthentication(uint64(m.SecurityThreshold))
	}
	l = len(m.Passcode)
	if l > 0 {
		n += 1 + l + sovAuthentication(uint64(l))
	}
	return n
}

func (m *RegisterStartResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AccountAddress)
	if l > 0 {
		n += 1 + l + sovAuthentication(uint64(l))
	}
	l = len(m.Aka)
	if l > 0 {
		n += 1 + l + sovAuthentication(uint64(l))
	}
	l = len(m.CreationOptions)
	if l > 0 {
		n += 1 + l + sovAuthentication(uint64(l))
	}
	l = len(m.SessionId)
	if l > 0 {
		n += 1 + l + sovAuthentication(uint64(l))
	}
	return n
}

func (m *RegisterFinishRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SessionId)
	if l > 0 {
		n += 1 + l + sovAuthentication(uint64(l))
	}
	l = len(m.CredentialResponse)
	if l > 0 {
		n += 1 + l + sovAuthentication(uint64(l))
	}
	return n
}

func (m *RegisterFinishResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovAuthentication(uint64(l))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovAuthentication(uint64(l))
	}
	if m.DidDocument != nil {
		l = m.DidDocument.Size()
		n += 1 + l + sovAuthentication(uint64(l))
	}
	if m.AccountInfo != nil {
		l = m.AccountInfo.Size()
		n += 1 + l + sovAuthentication(uint64(l))
	}
	l = len(m.UcanTokenHeader)
	if l > 0 {
		n += 1 + l + sovAuthentication(uint64(l))
	}
	return n
}

func (m *LoginStartRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Origin)
	if l > 0 {
		n += 1 + l + sovAuthentication(uint64(l))
	}
	l = len(m.AccountAddress)
	if l > 0 {
		n += 1 + l + sovAuthentication(uint64(l))
	}
	return n
}

func (m *LoginStartResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Success {
		n += 2
	}
	l = len(m.AccountAddress)
	if l > 0 {
		n += 1 + l + sovAuthentication(uint64(l))
	}
	l = len(m.Aka)
	if l > 0 {
		n += 1 + l + sovAuthentication(uint64(l))
	}
	l = len(m.CredentialOptions)
	if l > 0 {
		n += 1 + l + sovAuthentication(uint64(l))
	}
	return n
}

func (m *LoginFinishRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AccountAddress)
	if l > 0 {
		n += 1 + l + sovAuthentication(uint64(l))
	}
	l = len(m.CredentialResponse)
	if l > 0 {
		n += 1 + l + sovAuthentication(uint64(l))
	}
	return n
}

func (m *LoginFinishResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Success {
		n += 2
	}
	l = len(m.AccountAddress)
	if l > 0 {
		n += 1 + l + sovAuthentication(uint64(l))
	}
	if m.DidDocument != nil {
		l = m.DidDocument.Size()
		n += 1 + l + sovAuthentication(uint64(l))
	}
	if m.AccountInfo != nil {
		l = m.AccountInfo.Size()
		n += 1 + l + sovAuthentication(uint64(l))
	}
	l = len(m.UcanTokenHeader)
	if l > 0 {
		n += 1 + l + sovAuthentication(uint64(l))
	}
	return n
}

func sovAuthentication(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAuthentication(x uint64) (n int) {
	return sovAuthentication(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *RegisterStartRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAuthentication
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RegisterStartRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RegisterStartRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Origin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthentication
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthentication
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthentication
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Origin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeviceLabel", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthentication
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthentication
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthentication
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DeviceLabel = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SecurityThreshold", wireType)
			}
			m.SecurityThreshold = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthentication
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SecurityThreshold |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Passcode", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthentication
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthAuthentication
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthentication
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Passcode = append(m.Passcode[:0], dAtA[iNdEx:postIndex]...)
			if m.Passcode == nil {
				m.Passcode = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAuthentication(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAuthentication
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RegisterStartResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAuthentication
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RegisterStartResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RegisterStartResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccountAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthentication
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthentication
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthentication
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccountAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Aka", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthentication
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthentication
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthentication
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Aka = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreationOptions", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthentication
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthentication
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthentication
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CreationOptions = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SessionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthentication
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthentication
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthentication
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SessionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAuthentication(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAuthentication
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RegisterFinishRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAuthentication
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RegisterFinishRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RegisterFinishRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SessionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthentication
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthentication
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthentication
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SessionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CredentialResponse", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthentication
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthentication
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthentication
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CredentialResponse = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAuthentication(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAuthentication
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RegisterFinishResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAuthentication
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RegisterFinishResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RegisterFinishResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthentication
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthAuthentication
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthentication
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = append(m.Id[:0], dAtA[iNdEx:postIndex]...)
			if m.Id == nil {
				m.Id = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthentication
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthentication
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthentication
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DidDocument", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthentication
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAuthentication
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAuthentication
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DidDocument == nil {
				m.DidDocument = &types.DidDocument{}
			}
			if err := m.DidDocument.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccountInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthentication
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAuthentication
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAuthentication
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.AccountInfo == nil {
				m.AccountInfo = &AccountInfo{}
			}
			if err := m.AccountInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UcanTokenHeader", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthentication
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthAuthentication
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthentication
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UcanTokenHeader = append(m.UcanTokenHeader[:0], dAtA[iNdEx:postIndex]...)
			if m.UcanTokenHeader == nil {
				m.UcanTokenHeader = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAuthentication(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAuthentication
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LoginStartRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAuthentication
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LoginStartRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LoginStartRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Origin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthentication
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthentication
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthentication
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Origin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccountAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthentication
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthentication
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthentication
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccountAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAuthentication(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAuthentication
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LoginStartResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAuthentication
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LoginStartResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LoginStartResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Success", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthentication
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Success = bool(v != 0)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccountAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthentication
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthentication
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthentication
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccountAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Aka", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthentication
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthentication
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthentication
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Aka = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CredentialOptions", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthentication
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthentication
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthentication
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CredentialOptions = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAuthentication(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAuthentication
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LoginFinishRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAuthentication
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LoginFinishRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LoginFinishRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccountAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthentication
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthentication
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthentication
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccountAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CredentialResponse", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthentication
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthentication
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthentication
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CredentialResponse = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAuthentication(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAuthentication
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LoginFinishResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAuthentication
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LoginFinishResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LoginFinishResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Success", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthentication
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Success = bool(v != 0)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccountAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthentication
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAuthentication
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthentication
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccountAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DidDocument", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthentication
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAuthentication
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAuthentication
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DidDocument == nil {
				m.DidDocument = &types.DidDocument{}
			}
			if err := m.DidDocument.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccountInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthentication
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAuthentication
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAuthentication
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.AccountInfo == nil {
				m.AccountInfo = &AccountInfo{}
			}
			if err := m.AccountInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UcanTokenHeader", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAuthentication
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthAuthentication
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthAuthentication
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UcanTokenHeader = append(m.UcanTokenHeader[:0], dAtA[iNdEx:postIndex]...)
			if m.UcanTokenHeader == nil {
				m.UcanTokenHeader = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAuthentication(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAuthentication
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAuthentication(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAuthentication
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAuthentication
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAuthentication
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAuthentication
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAuthentication
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAuthentication
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAuthentication        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAuthentication          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAuthentication = fmt.Errorf("proto: unexpected end of group")
)
